version: "3"

services:
  database:
    image: postgres:12
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ratestask
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
      - ./data/data.sql:/docker-entrypoint-initdb.d/create_tables.sql
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    volumes:
      - ./ocean_freight:/application/ocean_freight/
